USE ICS_IT
CREATE TABLE SKU (
ID INT PRIMARY KEY IDENTITY,
Code VARCHAR(10) UNIQUE,
Name AS ('s' + ID)
);

CREATE TABLE Family 
(ID INT PRIMARY KEY IDENTITY, 
SurName VARCHAR(10), 
BudgetValue MONEY
);

CREATE TABLE Basket 
(ID INT PRIMARY KEY IDENTITY,
ID_SKU INT FOREIGN KEY REFERENCES SKU(ID),
ID_Family INT FOREIGN KEY REFERENCES Family (ID), 
Quantity INT CHECK(Quantity >= 0), 
Value INT CHECK(Value >= 0), 
PurchaseDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
DiscountValue INT
);